version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
