title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://joshjohanning-org.github.io/jekyll-github-pages-workflow-status/

aux_links:
  GitHub: https://github.com/joshjohanning-org
